# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [19]:
import numpy as np

#### Create an array of 10 zeros 

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

#### Create an array of the integers from 10 to 50

In [6]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create an array of all the even integers from 10 to 50

In [7]:
arr=np.arange(10,50)
arr[arr % 2 == 0]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
arr=np.arange(0,9)
reshaped=arr.reshape(3,3)
reshaped


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [10]:
np.random.rand(1)

array([0.30246071])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [11]:
np.random.randn(5, 5)

array([[-0.1461362 ,  0.9649953 ,  0.72517654, -0.62383777, -0.42634839],
       [ 0.35535072, -0.48423956, -1.42404472, -0.07805416,  0.55591416],
       [-1.63227895, -1.53674024, -0.87341234,  1.02683261,  0.0827814 ],
       [-0.0290583 , -1.15348623, -0.7510594 ,  1.26130572, -1.33599249],
       [-2.3170576 ,  1.01184736, -0.5462527 ,  0.00307156, -0.73965227]])

#### Create the following matrix:

In [12]:
arr=np.arange(0.01,1.0)
arr

array([0.01])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [13]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [14]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
mat[2,3::]

array([14, 15])

In [16]:
mat[3,4]

20

In [20]:
mat[4,]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [27]:
mat[3::,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [23]:
np.sum(mat)

325

325

#### Get the standard deviation of the values in mat

In [24]:
np.average(mat)

13.0

7.2111025509279782

#### Get the sum of all the columns in mat

In [26]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

array([55, 60, 65, 70, 75])

# Great Job!